<a href="https://colab.research.google.com/github/akashgardas/Deep-Learning/blob/feed-forward/models/feed_forward/Car_Price_Prediction_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Car Price Prediction

In [1]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

# Data Preparation and Processing

## Load Dataset

In [3]:
path = '/content/drive/MyDrive/Tek works/Deep-Learning/Datasets/CarPrice_dataset.csv'
df = pd.read_csv(path)
df.head()

   car_ID  symboling                   CarName  ... citympg highwaympg    price
0       1          3        alfa-romero giulia  ...      21         27  13495.0
1       2          3       alfa-romero stelvio  ...      21         27  16500.0
2       3          1  alfa-romero Quadrifoglio  ...      19         26  16500.0
3       4          2               audi 100 ls  ...      24         30  13950.0
4       5          2                audi 100ls  ...      18         22  17450.0

[5 rows x 26 columns]

## Inspect Data

In [ ]:
df.shape

(205, 26)

In [ ]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [ ]:
df.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

## Clean Data

In [ ]:
# Drop car_ID
df.drop('car_ID', axis=1, inplace=True)

In [ ]:
# Duplicates
df.duplicated().sum()

np.int64(0)

In [ ]:
# Missing values
df.isna().sum()

symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

## Separate Dataset

In [5]:
X = df.drop('price', axis=1)
y = df['price']

## Preprocessing

In [8]:
categorical_cols = X.select_dtypes(include=['object']).columns.tolist()
numerical_cols = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
print(categorical_cols)
print(numerical_cols)

['CarName', 'fueltype', 'aspiration', 'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'enginetype', 'cylindernumber', 'fuelsystem']
['car_ID', 'symboling', 'wheelbase', 'carlength', 'carwidth', 'carheight', 'curbweight', 'enginesize', 'boreratio', 'stroke', 'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg']

In [16]:
def get_processed_df(preprocessor, X_original):
    """
    Converts the output of a fitted ColumnTransformer back into a Pandas DataFrame.
    """
    # 1. Get the new feature names from the fitted preprocessor
    feature_names = preprocessor.get_feature_names_out()

    # 2. Get the transformed array and convert to dense if it's sparse
    X_array = preprocessor.transform(X_original)
    if hasattr(X_array, 'toarray'): # Check if it's a sparse matrix
        X_array = X_array.toarray()

    # 3. Create the new DataFrame, keeping the original index
    return pd.DataFrame(X_array, columns=feature_names, index=X_original.index)

In [17]:
# Define Preprocessing steps
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_cols)
    ],
    remainder='drop'  # Explicitly drop columns not specified (or use 'passthrough')
)

# Apply Preprocessing
preprocessor.fit(X)
X_processed = get_processed_df(preprocessor, X)

In [11]:
X.head()

   car_ID  symboling                   CarName  ... peakrpm citympg highwaympg
0       1          3        alfa-romero giulia  ...    5000      21         27
1       2          3       alfa-romero stelvio  ...    5000      21         27
2       3          1  alfa-romero Quadrifoglio  ...    5000      19         26
3       4          2               audi 100 ls  ...    5500      24         30
4       5          2                audi 100ls  ...    5500      18         22

[5 rows x 25 columns]

In [18]:
X_processed.head()

   num__car_ID  num__symboling  ...  cat__fuelsystem_spdi  cat__fuelsystem_spfi
0    -1.723622        1.743470  ...                   0.0                   0.0
1    -1.706724        1.743470  ...                   0.0                   0.0
2    -1.689826        0.133509  ...                   0.0                   0.0
3    -1.672928        0.938490  ...                   0.0                   0.0
4    -1.656029        0.938490  ...                   0.0                   0.0

[5 rows x 200 columns]

## Split train and test

In [20]:
X_train, X_test, y_train, y_test = train_test_split(X_processed, y, test_size=0.2, random_state=42)

# Model Design and Building

In [22]:
X_processed.shape

(205, 200)

## Model Architecture

```
Input Layer: Number of features = 25
Hidden Layer 1: 64 neurons (ReLU)
Hidden Layer 2: 32 neurons (ReLU)
Output Layer: 1 neuron (Price)
```

In [35]:
# Feedforward model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(128, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(64, activation='relu'),
    Dense(1)
])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 64)             │        12,864 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 128)            │         8,320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_9 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 29,505 (115.25 KB)

 Trainable params: 29,505 (115.25 KB)

 Non-trainable params: 0 (0.00 B)

## Compile the model

In [36]:
# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

## Train the model

In [37]:
# Train model
model.fit(X_train, y_train, epochs=200, batch_size=16, validation_split=0.2, verbose=0)

# Model Evaluation

In [38]:
# Test accuracy
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 221ms/step - loss: 9185319.0000
Test Loss: 8579033.0

In [39]:
y_pred = model.predict(X_test)

# Mean Absolute error
mae = mean_absolute_error(y_test, y_pred)

# Mean Squared error
mse = mean_squared_error(y_test, y_pred)

# Root mean square error
rmse = root_mean_squared_error(y_test, y_pred)

# R2 score
r2 = r2_score(y_test, y_pred)

print(f'MAE: {mae}')
print(f'MSE: {mse}')
print(f'RMSE: {rmse}')
print(f'R2 Score: {r2}')

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 198ms/step
MAE: 2005.7773673780487
MSE: 8579032.9932295
RMSE: 2928.998633190104
R2 Score: 0.8913276408062951

# Model Testing

In [40]:
sample_record = X_train.iloc[[0]]
predicted_price = model.predict(sample_record)

print(f"Sample record features:")
sample_record

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 221ms/step
Sample record features:

    num__car_ID  num__symboling  ...  cat__fuelsystem_spdi  cat__fuelsystem_spfi
66    -0.608337       -0.671472  ...                   0.0                   0.0

[1 rows x 200 columns]

In [41]:
print(f"Predicted Price for the sample record: {predicted_price[0][0]}")

Predicted Price for the sample record: 17195.091796875