<a href="https://colab.research.google.com/github/akashgardas/Deep-Learning/blob/feed-forward/models/feed_forward/Car_Price_Prediction_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Car Price Prediction

In [ ]:
import numpy as np
import pandas as pd
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

# Data Preparation and Processing

## Load Dataset

In [ ]:
path = '/content/drive/MyDrive/Tek works/Deep-Learning/Datasets/CarPrice_dataset.csv'
df = pd.read_csv(path)
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

## Inspect Data

In [ ]:
df.shape

(205, 26)

In [ ]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   car_ID            205 non-null    int64
 1   symboling         205 non-null    int64
 2   CarName           205 non-null    object
 3   fueltype          205 non-null    object
 4   aspiration        205 non-null    object
 5   doornumber        205 non-null    object
 6   carbody           205 non-null    object
 7   drivewheel        205 non-null    object
 8   enginelocation    205 non-null    object
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64
 14  enginetype        205 non-null    object
 15  cylindernumber    205 non-null    object
 16  enginesize        205 non-null    int64
 17  fuelsystem        205 non-null    object
 18  boreratio         205 non-null    float64
 19  stroke            205 non-null    float64
 20  compressionratio  205 non-null    float64
 21  horsepower        205 non-null    int64
 22  peakrpm           205 non-null    int64
 23  citympg           205 non-null    int64
 24  highwaympg        205 non-null    int64
 25  price             205 non-null    float64
dtypes: float64(8), int64(8), object(10)
memory usage: 41.8+ KB

In [ ]:
df.describe()

,car_ID,symboling,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,103.000000,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,3.329756,3.255415,10.142537,104.117073,5125.121951,25.219512,30.751220,13276.710571
std,59.322565,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,0.270844,0.313597,3.972040,39.544167,476.985643,6.542142,6.886443,7988.852332
min,1.000000,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,2.540000,2.070000,7.000000,48.000000,4150.000000,13.000000,16.000000,5118.000000
25%,52.000000,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,3.150000,3.110000,8.600000,70.000000,4800.000000,19.000000,25.000000,7788.000000
50%,103.000000,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,3.310000,3.290000,9.000000,95.000000,5200.000000,24.000000,30.000000,10295.000000
75%,154.000000,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,3.580000,3.410000,9.400000,116.000000,5500.000000,30.000000,34.000000,16503.000000
max,205.000000,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,3.940000,4.170000,23.000000,288.000000,6600.000000,49.000000,54.000000,45400.000000

## Clean Data

In [ ]:
# Drop car_ID
df.drop('car_ID', axis=1, inplace=True)

In [ ]:
# Duplicates
df.duplicated().sum()

np.int64(0)

In [ ]:
# Missing values
df.isna().sum()

symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

## Encode Categorical Columns

In [ ]:
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
print(categorical_cols)

['CarName', 'fueltype', 'aspiration', 'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'enginetype', 'cylindernumber', 'fuelsystem']

In [ ]:
label_encoder = LabelEncoder()
for col in categorical_cols:
    df[col] = label_encoder.fit_transform(df[col])

print("DataFrame Info after Label Encoding:")
df.info()

print("\nDataFrame Head after Label Encoding:")
df.head()

DataFrame Info after Label Encoding:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 25 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   symboling         205 non-null    int64
 1   CarName           205 non-null    int64
 2   fueltype          205 non-null    int64
 3   aspiration        205 non-null    int64
 4   doornumber        205 non-null    int64
 5   carbody           205 non-null    int64
 6   drivewheel        205 non-null    int64
 7   enginelocation    205 non-null    int64
 8   wheelbase         205 non-null    float64
 9   carlength         205 non-null    float64
 10  carwidth          205 non-null    float64
 11  carheight         205 non-null    float64
 12  curbweight        205 non-null    int64
 13  enginetype        205 non-null    int64
 14  cylindernumber    205 non-null    int64
 15  enginesize        205 non-null    int64
 16  fuelsystem        205 non-null    int64
 17  boreratio         205 non-null    float64
 18  stroke            205 non-null    float64
 19  compressionratio  205 non-null    float64
 20  horsepower        205 non-null    int64
 21  peakrpm           205 non-null    int64
 22  citympg           205 non-null    int64
 23  highwaympg        205 non-null    int64
 24  price             205 non-null    float64
dtypes: float64(8), int64(17)
memory usage: 40.2 KB

DataFrame Head after Label Encoding:

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,3,2,1,0,1,0,2,0,88.6,168.8,...,130,5,3.47,2.68,9.0,111,5000,21,27,13495.0
1,3,3,1,0,1,0,2,0,88.6,168.8,...,130,5,3.47,2.68,9.0,111,5000,21,27,16500.0
2,1,1,1,0,1,2,2,0,94.5,171.2,...,152,5,2.68,3.47,9.0,154,5000,19,26,16500.0
3,2,4,1,0,0,3,1,0,99.8,176.6,...,109,5,3.19,3.40,10.0,102,5500,24,30,13950.0
4,2,5,1,0,0,3,0,0,99.4,176.6,...,136,5,3.19,3.40,8.0,115,5500,18,22,17450.0

## Standardize numerical features

In [ ]:
# Standard scaler
scaler = StandardScaler()
df[numerical_cols] = scaler.fit_transform(df[numerical_cols])

## Split Dataset

In [ ]:
X = df.drop('price', axis=1)
y = df['price']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model Design and Building

In [ ]:
df.shape

(205, 25)

## Model Architecture

```
Input Layer: Number of features = 25
Hidden Layer 1: 64 neurons (ReLU)
Hidden Layer 2: 32 neurons (ReLU)
Output Layer: 1 neuron (Price)
```

In [ ]:
# Feedforward model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)
])

model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         1,600 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,713 (14.50 KB)

 Trainable params: 3,713 (14.50 KB)

 Non-trainable params: 0 (0.00 B)

## Compile the model

In [ ]:
# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

## Train the model

In [ ]:
# Train model
model.fit(X_train, y_train, epochs=200, batch_size=16, validation_split=0.2)

Epoch 1/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 3s 128ms/step - loss: 45.2426 - val_loss: 2.6169
Epoch 2/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 5.9347 - val_loss: 5.4534
Epoch 3/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 3.2515 - val_loss: 1.7471
Epoch 4/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 1.2814 - val_loss: 0.9951
Epoch 5/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.4625 - val_loss: 0.9705
Epoch 6/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.7340 - val_loss: 0.5424
Epoch 7/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.4039 - val_loss: 0.4831
Epoch 8/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2738 - val_loss: 0.4135
Epoch 9/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2709 - val_loss: 0.3821
Epoch 10/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2255 - val_loss: 0.3339
Epoch 11/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.2104 - val_loss: 0.3195
Epoch 12/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1947 - val_loss: 0.3187
Epoch 13/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2525 - val_loss: 0.3042
Epoch 14/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.2565 - val_loss: 0.2901
Epoch 15/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1969 - val_loss: 0.2706
Epoch 16/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1796 - val_loss: 0.2566
Epoch 17/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1629 - val_loss: 0.2521
Epoch 18/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1700 - val_loss: 0.2598
Epoch 19/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1926 - val_loss: 0.2586
Epoch 20/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.1538 - val_loss: 0.2437
Epoch 21/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1497 - val_loss: 0.2345
Epoch 22/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1498 - val_loss: 0.2279
Epoch 23/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1612 - val_loss: 0.2426
Epoch 24/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1229 - val_loss: 0.2247
Epoch 25/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1196 - val_loss: 0.2144
Epoch 26/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1294 - val_loss: 0.2123
Epoch 27/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1699 - val_loss: 0.2015
Epoch 28/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1026 - val_loss: 0.1959
Epoch 29/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1201 - val_loss: 0.1960
Epoch 30/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0949 - val_loss: 0.1969
Epoch 31/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0893 - val_loss: 0.1969
Epoch 32/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0923 - val_loss: 0.1901
Epoch 33/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0954 - val_loss: 0.1845
Epoch 34/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1072 - val_loss: 0.1793
Epoch 35/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1341 - val_loss: 0.1908
Epoch 36/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1362 - val_loss: 0.1976
Epoch 37/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1229 - val_loss: 0.1979
Epoch 38/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1007 - val_loss: 0.1788
Epoch 39/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1180 - val_loss: 0.1764
Epoch 40/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0844 - val_loss: 0.1636
Epoch 41/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.1178 - val_loss: 0.1728
Epoch 42/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0724 - val_loss: 0.1629
Epoch 43/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0891 - val_loss: 0.1581
Epoch 44/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0865 - val_loss: 0.1625
Epoch 45/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0840 - val_loss: 0.1685
Epoch 46/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1014 - val_loss: 0.1900
Epoch 47/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0828 - val_loss: 0.1535
Epoch 48/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0883 - val_loss: 0.1500
Epoch 49/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0906 - val_loss: 0.1823
Epoch 50/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0980 - val_loss: 0.1570
Epoch 51/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0956 - val_loss: 0.1511
Epoch 52/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0721 - val_loss: 0.1586
Epoch 53/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0727 - val_loss: 0.1486
Epoch 54/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0761 - val_loss: 0.1518
Epoch 55/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0794 - val_loss: 0.1582
Epoch 56/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0641 - val_loss: 0.1499
Epoch 57/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0720 - val_loss: 0.1580
Epoch 58/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0741 - val_loss: 0.1684
Epoch 59/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0702 - val_loss: 0.2011
Epoch 60/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0877 - val_loss: 0.1626
Epoch 61/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.1073 - val_loss: 0.1648
Epoch 62/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0809 - val_loss: 0.1933
Epoch 63/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0872 - val_loss: 0.1438
Epoch 64/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0654 - val_loss: 0.1725
Epoch 65/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0997 - val_loss: 0.1502
Epoch 66/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0840 - val_loss: 0.1627
Epoch 67/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0582 - val_loss: 0.1409
Epoch 68/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0616 - val_loss: 0.1372
Epoch 69/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0443 - val_loss: 0.1408
Epoch 70/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0515 - val_loss: 0.1349
Epoch 71/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0569 - val_loss: 0.1362
Epoch 72/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0448 - val_loss: 0.1406
Epoch 73/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0537 - val_loss: 0.1390
Epoch 74/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0665 - val_loss: 0.1345
Epoch 75/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0522 - val_loss: 0.1752
Epoch 76/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0768 - val_loss: 0.1334
Epoch 77/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0575 - val_loss: 0.1571
Epoch 78/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0510 - val_loss: 0.1377
Epoch 79/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0578 - val_loss: 0.1361
Epoch 80/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0486 - val_loss: 0.1317
Epoch 81/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0502 - val_loss: 0.1390
Epoch 82/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0564 - val_loss: 0.1613
Epoch 83/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0653 - val_loss: 0.1337
Epoch 84/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0516 - val_loss: 0.1277
Epoch 85/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0544 - val_loss: 0.1733
Epoch 86/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1057 - val_loss: 0.1285
Epoch 87/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0839 - val_loss: 0.1552
Epoch 88/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0660 - val_loss: 0.1191
Epoch 89/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0442 - val_loss: 0.1194
Epoch 90/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0446 - val_loss: 0.1221
Epoch 91/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0506 - val_loss: 0.1311
Epoch 92/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0472 - val_loss: 0.1242
Epoch 93/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0436 - val_loss: 0.1189
Epoch 94/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0408 - val_loss: 0.1302
Epoch 95/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0571 - val_loss: 0.1460
Epoch 96/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0570 - val_loss: 0.1219
Epoch 97/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0416 - val_loss: 0.1207
Epoch 98/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0396 - val_loss: 0.1489
Epoch 99/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0662 - val_loss: 0.1414
Epoch 100/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0663 - val_loss: 0.1518
Epoch 101/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0788 - val_loss: 0.1235
Epoch 102/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0496 - val_loss: 0.1307
Epoch 103/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0430 - val_loss: 0.1127
Epoch 104/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0395 - val_loss: 0.1147
Epoch 105/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0376 - val_loss: 0.1162
Epoch 106/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0557 - val_loss: 0.1143
Epoch 107/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0386 - val_loss: 0.1130
Epoch 108/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0415 - val_loss: 0.1204
Epoch 109/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0432 - val_loss: 0.1401
Epoch 110/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0632 - val_loss: 0.1169
Epoch 111/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0384 - val_loss: 0.1193
Epoch 112/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0502 - val_loss: 0.1710
Epoch 113/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0715 - val_loss: 0.1112
Epoch 114/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0546 - val_loss: 0.1203
Epoch 115/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0559 - val_loss: 0.1106
Epoch 116/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0557 - val_loss: 0.1619
Epoch 117/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0662 - val_loss: 0.1130
Epoch 118/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0373 - val_loss: 0.1081
Epoch 119/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0405 - val_loss: 0.1251
Epoch 120/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0727 - val_loss: 0.1128
Epoch 121/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0715 - val_loss: 0.1525
Epoch 122/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0649 - val_loss: 0.1983
Epoch 123/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0755 - val_loss: 0.1111
Epoch 124/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0432 - val_loss: 0.1110
Epoch 125/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0325 - val_loss: 0.1099
Epoch 126/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0402 - val_loss: 0.1129
Epoch 127/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0384 - val_loss: 0.1130
Epoch 128/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0342 - val_loss: 0.1140
Epoch 129/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0378 - val_loss: 0.1085
Epoch 130/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0375 - val_loss: 0.1108
Epoch 131/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0301 - val_loss: 0.1223
Epoch 132/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0487 - val_loss: 0.1161
Epoch 133/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0357 - val_loss: 0.1134
Epoch 134/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0403 - val_loss: 0.1125
Epoch 135/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0394 - val_loss: 0.1290
Epoch 136/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0482 - val_loss: 0.1132
Epoch 137/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0435 - val_loss: 0.1116
Epoch 138/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0377 - val_loss: 0.1413
Epoch 139/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0425 - val_loss: 0.1154
Epoch 140/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0363 - val_loss: 0.1498
Epoch 141/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0563 - val_loss: 0.1351
Epoch 142/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0591 - val_loss: 0.1110
Epoch 143/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0607 - val_loss: 0.1174
Epoch 144/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0501 - val_loss: 0.1048
Epoch 145/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0440 - val_loss: 0.1024
Epoch 146/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0332 - val_loss: 0.1119
Epoch 147/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0413 - val_loss: 0.1133
Epoch 148/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0255 - val_loss: 0.1177
Epoch 149/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0348 - val_loss: 0.1022
Epoch 150/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0497 - val_loss: 0.1018
Epoch 151/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0375 - val_loss: 0.1110
Epoch 152/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0393 - val_loss: 0.1087
Epoch 153/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0513 - val_loss: 0.1267
Epoch 154/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0628 - val_loss: 0.1182
Epoch 155/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0405 - val_loss: 0.1123
Epoch 156/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0322 - val_loss: 0.1114
Epoch 157/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0342 - val_loss: 0.1111
Epoch 158/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 0.0332 - val_loss: 0.1141
Epoch 159/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0410 - val_loss: 0.1058
Epoch 160/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0416 - val_loss: 0.1028
Epoch 161/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0427 - val_loss: 0.1052
Epoch 162/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0366 - val_loss: 0.1104
Epoch 163/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0376 - val_loss: 0.1101
Epoch 164/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0325 - val_loss: 0.1056
Epoch 165/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0271 - val_loss: 0.1049
Epoch 166/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0313 - val_loss: 0.1108
Epoch 167/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: 0.0363 - val_loss: 0.1144
Epoch 168/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 0.0309 - val_loss: 0.1073
Epoch 169/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0450 - val_loss: 0.1081
Epoch 170/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0361 - val_loss: 0.1057
Epoch 171/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0377 - val_loss: 0.1105
Epoch 172/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0358 - val_loss: 0.1096
Epoch 173/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0275 - val_loss: 0.1048
Epoch 174/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0407 - val_loss: 0.0999
Epoch 175/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0384 - val_loss: 0.1154
Epoch 176/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 0.0372 - val_loss: 0.1086
Epoch 177/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0273 - val_loss: 0.1072
Epoch 178/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0316 - val_loss: 0.1220
Epoch 179/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0406 - val_loss: 0.1280
Epoch 180/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0399 - val_loss: 0.1215
Epoch 181/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0360 - val_loss: 0.1398
Epoch 182/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0409 - val_loss: 0.1465
Epoch 183/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0386 - val_loss: 0.1027
Epoch 184/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0271 - val_loss: 0.1228
Epoch 185/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0370 - val_loss: 0.1448
Epoch 186/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0530 - val_loss: 0.1157
Epoch 187/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0349 - val_loss: 0.0999
Epoch 188/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0288 - val_loss: 0.1009
Epoch 189/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0288 - val_loss: 0.1177
Epoch 190/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0288 - val_loss: 0.0997
Epoch 191/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0257 - val_loss: 0.1189
Epoch 192/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0367 - val_loss: 0.1131
Epoch 193/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0255 - val_loss: 0.1028
Epoch 194/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0318 - val_loss: 0.1069
Epoch 195/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0277 - val_loss: 0.1253
Epoch 196/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0421 - val_loss: 0.1431
Epoch 197/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0354 - val_loss: 0.1026
Epoch 198/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0278 - val_loss: 0.1043
Epoch 199/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0307 - val_loss: 0.1042
Epoch 200/200
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0330 - val_loss: 0.1063

# Model Evaluation

In [ ]:
# Test accuracy
loss = model.evaluate(X_test, y_test)
print(f'Test Loss: {loss}')

2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 255ms/step - loss: 0.1360
Test Loss: 0.12743566930294037

In [ ]:
y_pred = model.predict(X_test)

# Mean Absolute error
mae = mean_absolute_error(y_test, y_pred)

# Mean Squared error
mse = mean_squared_error(y_test, y_pred)

# Root mean square error
rmse = root_mean_squared_error(y_test, y_pred)

# R2 score
r2 = r2_score(y_test, y_pred)

print(f'MAE: {mae}')
print(f'MSE: {mse}')
print(f'RMSE: {rmse}')
print(f'R2 Score: {r2}')

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 196ms/step
MAE: 0.25915609931159034
MSE: 0.1274356700337676
RMSE: 0.3569813300913195
R2 Score: 0.897478050086393

# Model Testing

In [ ]:
sample_record = X_train.iloc[[0]]
predicted_price = model.predict(sample_record)

print(f"Sample record features:")
sample_record

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
Sample record features:

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
66,-0.671472,60,0,0,0,3,2,0,1.022697,0.07725,...,2,0.170739,3,0.371023,1.22937,2.99254,-0.814171,-1.944265,0.88574,1.200761

In [ ]:
print(f"Predicted Price for the sample record: {predicted_price[0][0]}")

Predicted Price for the sample record: -0.1322266012430191

In [ ]:
X_train

,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,cylindernumber,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
66,-0.671472,60,0,0,0,3,2,0,1.022697,0.077250,...,2,0.170739,3,0.371023,1.229370,2.992540,-0.814171,-1.944265,0.885740,1.200761
111,-0.671472,85,1,0,0,3,2,0,1.522109,1.027916,...,2,-0.166277,5,0.482059,-3.405717,-0.439775,-0.231119,-0.262960,-0.953012,-0.982764
153,-0.671472,121,1,0,0,4,1,0,-0.508831,-0.353393,...,2,-0.840310,1,-1.035435,-0.720563,-0.288349,-1.067671,-0.683286,0.885740,0.909625
96,0.133509,76,1,0,0,3,1,0,-0.708596,-0.710909,...,2,-0.719947,1,-0.665314,0.110556,-0.187398,-0.890221,0.157366,0.885740,0.909625
38,-0.671472,41,1,0,1,2,1,0,-0.375655,-0.532151,...,2,-0.407003,0,-0.665314,1.037573,-0.288349,-0.459269,1.418345,0.272823,0.327351
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
106,0.133509,70,1,0,1,2,2,0,0.073815,0.361638,...,3,1.302152,5,0.371023,0.046624,-0.288349,1.416637,0.157366,-0.953012,-0.837195
14,0.133509,15,1,0,0,3,2,0,0.789639,1.214799,...,3,0.892917,5,-0.073121,-0.209105,-0.288349,0.427984,-1.839184,-0.799782,-0.837195
92,0.133509,76,1,0,0,3,1,0,-0.708596,-0.710909,...,2,-0.719947,1,-0.665314,0.110556,-0.187398,-0.890221,0.157366,0.885740,0.909625
179,1.743470,120,1,0,1,2,2,0,0.689756,0.767905,...,3,1.061426,5,-0.221170,0.302353,-0.212636,1.441987,0.157366,-0.953012,-0.982764
102,-0.671472,72,1,0,0,4,1,0,0.273580,0.857284,...,3,1.302152,5,0.371023,0.046624,-0.288349,1.213836,0.157366,-1.259470,-1.273900